apiVersion: v1
kind: Service
metadata:
  name: azblobuploaderservice
spec:
  selector:
    app: azblobuploader
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer